// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "profiles": string;
      "activeProfileId": string;
      "migratedToProfilesV3": boolean;
      "summaryPrompt": string;
      "promptVersion": number;
      "truncateLength": string;
    };
  }
}
