// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "provider": string;
      "apiKey": string;
      "apiUrl": string;
      "model": string;
      "temperature": string;
      "stream": boolean;
      "summaryPrompt": string;
      "truncateLength": string;
    };
  }
}
